dist: xenial
language: python
cache: pip

services:
  - postgresql
  - mysql

python:
  - "3.7"

env:
  - TESTING_DB=sqlite3
  - TESTING_DB=postgresql
  - TESTING_DB=mysql

before_install: 

  - psql -U postgres -c "CREATE DATABASE evennia;"
  - psql -U postgres -c "CREATE USER evennia WITH PASSWORD 'password';"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE evennia TO evennia;"
  - mysql -u root -e "CREATE DATABASE evennia;"
  - mysql -u root -e "CREATE USER 'evennia'@'localhost' IDENTIFIED BY 'password';"
  - mysql -u root -e "ALTER DATABASE evennia CHARACTER SET utf8;"
  - mysql --database=evennia -u root -e "GRANT ALL PRIVILEGES ON evennia.* TO 'evennia'@'localost'; FLUSH PRIVILEGES;"

install:
  - pip install psycopg2-binary
  - pip install mysqlclient
  - pip install -e .
  - pip install coveralls

before_script:
  - python -VV
  - evennia --init testing_mygame
  - cp .travis/testing_settings.py testing_mygame/server/conf/settings.py
  - cd testing_mygame
  - evennia migrate

script:
  - coverage run --source=../evennia --omit=*/migrations/*,*/urls.py,*/test*.py,*.sh,*.txt,*.md,*.pyc,*.service ../bin/unix/evennia test evennia

after_success:
  - coveralls
